### ISSUE TITLE
Use const instead of ler if possible

### ISSUE THREAD

**Issue by tshemsedinov** [vchamelin/Kurs4ch#5]
in cases like this https://github.com/vchamelin/Kurs4ch/blob/6b81d3d57c5781bd2452b882931c82c0424a5306/js/likeBtn.js#L8

**Comment by cmertenok** [comment]
В данном случаи мы не можем использовать const, так как далее мы перезаписываем массив.

**Comment by tshemsedinov** [comment]
Вот от перезаписывания и нужно избавиться
