### ISSUE TITLE
Decompose long procedures

### ISSUE THREAD

**Issue by tshemsedinov** [vchamelin/Kurs4ch#6]
Like this https://github.com/vchamelin/Kurs4ch/blob/6b81d3d57c5781bd2452b882931c82c0424a5306/js/infoPostAdd.js#L138 or this https://github.com/vchamelin/Kurs4ch/blob/6b81d3d57c5781bd2452b882931c82c0424a5306/js/addLikePosts.js#L3-L102

**Comment by amelinvch** [comment]
Разложили функции. Спасибо 😄.

**Comment by tshemsedinov** [comment]
Было бы лучше, если бы вынули функции из обработчика события на верхний уровень
